package view;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author pyade 
 */
import java.sql.SQLException;
import java.util.List;
import model.Course;
import controller.CourseController;
import javax.swing.table.DefaultTableModel;


public class CourseForm extends javax.swing.JFrame {

    private List<Course> listCourse;
    private int selectedCourseIndex = -1;
    private String selectedCourseCode = "";
    private final CourseController controller = new CourseController(); 

    public CourseForm() throws SQLException {
        initComponents();
        loadCourseData(); 
    }

    private void loadCourseData() {
        try {
            listCourse = controller.getAllCourses();
            updateTable(listCourse);

            if (listCourse != null && !listCourse.isEmpty()) {
                showCourseAt(0);
            } else {
                clearForm();
            }
        } catch (Exception e) {
            System.err.println("Gagal memuat data dari database: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void updateTable(List<Course> courses) {
        String[][] data = new String[courses.size()][4];

        for (int i = 0; i < courses.size(); i++) {
            Course course = courses.get(i);
            data[i][0] = course.getCode();
            data[i][1] = course.getCourseName();
            data[i][2] = String.valueOf(course.getSKS());
            data[i][3] = String.valueOf(course.getSemester());
        }

        String[] columnName = {"Code", "Nama Mata Kuliah", "SKS", "Semester"};
        jTableCourse.setModel(new DefaultTableModel(data, columnName));

        javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        jTableCourse.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        jTableCourse.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
    }

    private void showCourseAt(int index) {
        if (listCourse == null || index < 0 || index >= listCourse.size()) {
            return;
        }

        Course course = listCourse.get(index);
        selectedCourseIndex = index;
        selectedCourseCode = course.getCode();

        jTextFieldCode.setText(course.getCode());
        jTextFieldNama.setText(course.getCourseName());
        jTextFieldSKS.setText(String.valueOf(course.getSKS()));
        jTextFieldSemester.setText(String.valueOf(course.getSemester()));
        jTextFieldCode.setEditable(false);

        if (jTableCourse.getRowCount() > index) {
            jTableCourse.setRowSelectionInterval(index, index);
            jTableCourse.scrollRectToVisible(jTableCourse.getCellRect(index, 0, true));
        }
    }

    private void clearForm() {
        jTextFieldNama.setText("");
        jTextFieldCode.setText("");
        jTextFieldSemester.setText("");
        jTextFieldSKS.setText("");
        selectedCourseIndex = -1;
        selectedCourseCode = "";
        jTextFieldCode.setEditable(true);
        
        jTextFieldCode.requestFocus();
    }

    private boolean isFormIncomplete(String courseName, String sksText, String code, String semesterText) {
        return courseName.isEmpty() || courseName.equals("Nama")
                || sksText.isEmpty() || sksText.equals("Sks")
                || code.isEmpty() || code.equals("Code")
                || semesterText.isEmpty() || semesterText.equals("Semester");
    }

    private Course buildCourseFromForm() {
        String courseName = jTextFieldNama.getText().trim();
        String sksText = jTextFieldSKS.getText().trim();
        String code = jTextFieldCode.getText().trim();
        String semesterText = jTextFieldSemester.getText().trim();

        if (isFormIncomplete(courseName, sksText, code, semesterText)) {
            return null;
        }

        return new Course(code, courseName, Integer.parseInt(sksText), Integer.parseInt(semesterText));
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldCode = new javax.swing.JTextField();
        jTextFieldNama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldSKS = new javax.swing.JTextField();
        jTextFieldSearch = new javax.swing.JTextField();
        jToggleButtonSearch = new javax.swing.JToggleButton();
        jTextFieldSemester = new javax.swing.JTextField();
        jButtonSimpan = new javax.swing.JButton();
        jToggleButtonDelete = new javax.swing.JToggleButton();
        jToggleButtonBatal = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableCourse = new javax.swing.JTable();
        jButtonPrev = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Course");

        jTextFieldCode.setText("Code");

        jTextFieldNama.setText("Nama");

        jLabel5.setText("SKS");

        jTextFieldSKS.setText("Sks");
        jTextFieldSKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSKSActionPerformed(evt);
            }
        });

        jTextFieldSearch.setText("Pencarian");

        jToggleButtonSearch.setText("Cari");
        jToggleButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSearchActionPerformed(evt);
            }
        });

        jTextFieldSemester.setText("Semester");

        jButtonSimpan.setText("Simpan");
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });

        jToggleButtonDelete.setForeground(new java.awt.Color(255, 0, 51));
        jToggleButtonDelete.setText("Delete");
        jToggleButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonDeleteActionPerformed(evt);
            }
        });

        jToggleButtonBatal.setText("Batal");
        jToggleButtonBatal.setToolTipText("");
        jToggleButtonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonBatalActionPerformed(evt);
            }
        });

        jLabel7.setText("NAMA");

        jLabel8.setText("CODE");

        jLabel9.setText("Semester");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCode)
                            .addComponent(jTextFieldNama, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(jTextFieldSKS))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jToggleButtonBatal)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButtonDelete)
                                .addGap(12, 12, 12)
                                .addComponent(jButtonSimpan)))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSimpan)
                            .addComponent(jToggleButtonDelete)
                            .addComponent(jToggleButtonBatal))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonSearch))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane4.setPreferredSize(new java.awt.Dimension(300, 80));

        jTableCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableCourse.setFillsViewportHeight(true);
        jTableCourse.setShowGrid(false);
        jTableCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCourseMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableCourse);

        jButtonPrev.setText("<<Prev");
        jButtonPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrevActionPerformed(evt);
            }
        });

        jButtonNext.setText("Next>>");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel6.setText("InputData");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonPrev)
                        .addGap(35, 35, 35)
                        .addComponent(jButtonNext)
                        .addGap(214, 214, 214))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(262, 262, 262)))
                        .addGap(17, 17, 17))))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNext)
                    .addComponent(jButtonPrev))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        try {
            Course course = buildCourseFromForm();

            if (course == null) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Semua data kolom mata kuliah harus terisi!",
                        "Peringatan",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            int hasil;

            if (selectedCourseCode.isEmpty()) {
                hasil = controller.create(course);
            }else{
                hasil = controller.update(course, selectedCourseCode);
            }

            if (hasil == 1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Data Course berhasil disimpan ke database");
                loadCourseData(); 
                clearForm();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Gagal menyimpan data.",
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Terjadi kesalahan sistem: " + e.getMessage(),
                    "Error Fatal",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jButtonPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrevActionPerformed
        // TODO add your handling code here:
        if (listCourse == null || listCourse.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Belum ada data mata kuliah pada tabel");
            return;
        }
        if (selectedCourseIndex > 0) {
            showCourseAt(selectedCourseIndex - 1);
        }
    }//GEN-LAST:event_jButtonPrevActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        // TODO add your handling code here:
        if (listCourse == null || listCourse.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Belum ada data mata kuliah pada tabel");
            return;
        }
        if (selectedCourseIndex < listCourse.size() - 1) {
            showCourseAt(selectedCourseIndex + 1);
        }
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jToggleButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonDeleteActionPerformed
        // TODO add your handling code here:


        if (selectedCourseCode == null || selectedCourseCode.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Pilih data tabel mata kuliah terlebih dahulu", 
                    "Peringatan", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Munculkan peringatan konfirmasi penghapusan
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Apakah anda yakin untuk menghapus data mata kuliah ini? ",
                "Delete Confirmation",
                javax.swing.JOptionPane.YES_NO_OPTION
        );


        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try {
                controller.deleteCourse(selectedCourseCode);
              
                javax.swing.JOptionPane.showMessageDialog(this, "Course deleted successfully!");
                this.clearForm(); 

                loadCourseData();

            } catch (Exception ex) {
                System.err.println("Error saat menghapus data course: " + ex.getMessage());
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Deleted unsuccessfully! Terjadi kesalahan pada sistem.",
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jToggleButtonDeleteActionPerformed

    private void jTableCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCourseMouseClicked
        // TODO add your handling code here:
        selectedCourseIndex = jTableCourse.getSelectedRow();
        if(selectedCourseIndex >= 0) {
            showCourseAt(selectedCourseIndex);
        }
    }//GEN-LAST:event_jTableCourseMouseClicked

    private void jToggleButtonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonBatalActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_jToggleButtonBatalActionPerformed

    private void jToggleButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSearchActionPerformed
        // TODO add your handling code here:
       String searchKeyword = jTextFieldSearch.getText().trim();
        
        List<Course> dataHasil;

        if (searchKeyword.isEmpty() || searchKeyword.equals("Pencarian")) {
            dataHasil = controller.getAllCourses(); 
        } else {
            dataHasil = controller.searchCourse(searchKeyword); 
        }

        listCourse = dataHasil;
        updateTable(listCourse);
        

        if (jTableCourse.getRowCount() > 0) {
            showCourseAt(0); 
            
        } else {
            clearForm();
           
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Data mata kuliah tidak ditemukan!",
                    "Pencarian",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jToggleButtonSearchActionPerformed

    private void jTextFieldSKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSKSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSKSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(CourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(CourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(CourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(CourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            try {
                // Panggil form LecturerForm di dalam try-catch
                new CourseForm().setVisible(true);
            } catch (java.sql.SQLException ex) {
                // Menangkap error lemparan (throws) dari konstruktor
                java.util.logging.Logger.getLogger(CourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrev;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTableCourse;
    private javax.swing.JTextField jTextFieldCode;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldSKS;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JTextField jTextFieldSemester;
    private javax.swing.JToggleButton jToggleButtonBatal;
    private javax.swing.JToggleButton jToggleButtonDelete;
    private javax.swing.JToggleButton jToggleButtonSearch;
    // End of variables declaration//GEN-END:variables
}
