package view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author pyade 
 */
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Lecturer;
import controller.LecturerController;
import dao.LecturerDAO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;

public class LecturerForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Lecturer.class.getName());

    private String selectedNIDN;
    private String selectedName;
//    private ArrayList<Lecturer> listLecturer;
    private List<Lecturer> listDosen;
    private int currentIndex = 0;
    private String nidnLama = "";
    LecturerController controller = new LecturerController();

    /**
     * Creates new form Lecturer
     */
    public LecturerForm() throws SQLException {
        initComponents();
        loadLecturerData();
    }

    @SuppressWarnings("unchecked")
    private void loadLecturerData() throws SQLException {
        try {
//            List<Lecturer> lecturers = controller.getLecturer();
            listDosen = controller.getLecturer();
            String[][] data = new String[listDosen.size()][4];

            for (int i = 0; i < listDosen.size(); i++) {
                data[i][0] = listDosen.get(i).getName();
                data[i][1] = listDosen.get(i).getIdCard();
                data[i][2] = listDosen.get(i).getNidn();
                data[i][3] = listDosen.get(i).getExpertise();
            }

            String[] columnName = {"Name", "ID", "NIDN", "Expertise"};
            jTableLecturer.setModel(new javax.swing.table.DefaultTableModel(data, columnName));

        } catch (Exception e) {
            
            System.err.println("Gagal memuat data dari database: " + e.getMessage());
            e.printStackTrace();
        }
    }

     private void tampilkanData(int index) {
       try {
            if (index >= 0 && index < jTableLecturer.getRowCount()) {
              
                String name = jTableLecturer.getValueAt(index, 0).toString();
                String nik = jTableLecturer.getValueAt(index, 1).toString();
                String nidn = jTableLecturer.getValueAt(index, 2).toString();
                String expertise = jTableLecturer.getValueAt(index, 3).toString();


                jTextFieldNama.setText(name);
                jTextFieldCardID.setText(nik);     
                jTextFieldNIDN.setText(nidn);
                jTextFieldExpertise.setText(expertise);
                
             
                jTextFieldNIDN.setEditable(false);
                

                this.selectedNIDN = nidn;
                this.nidnLama = nidn;
            }
        } catch (Exception e) {
            System.err.println("Gagal menampilkan data ke form: " + e.getMessage());
            e.printStackTrace();
        }
    }
    private void refreshLecturerTable(List<Lecturer> dataList) {
       
        this.listDosen = dataList; 
        

        DefaultTableModel model = (DefaultTableModel) jTableLecturer.getModel();
        model.setRowCount(0);

 
        for (Lecturer r : dataList) {
            Object[] newLine = new Object[]{
                r.getName(),
                r.getIdCard(),
                r.getNidn(),
                r.getExpertise()
            };
            model.addRow(newLine);
        }

       
        if (jTableLecturer.getRowCount() > 0) {
            jTableLecturer.setRowSelectionInterval(0, 0);
            currentIndex = 0; 
            tampilkanData(currentIndex);
        }
    }
    private void clearForm() {
        jTextFieldNama.setText("");
        jTextFieldCardID.setText("");
        jTextFieldExpertise.setText("");
        jTextFieldNIDN.setText("");
        this.nidnLama = "";
        this.selectedNIDN = "";
//        jTextFieldNIDN.setEditable(true);
        jTextFieldNIDN.setEditable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldCardID = new javax.swing.JTextField();
        jTextFieldNama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNIDN = new javax.swing.JTextField();
        jTextFieldSearch = new javax.swing.JTextField();
        jToggleButtonSearch = new javax.swing.JToggleButton();
        jTextFieldExpertise = new javax.swing.JTextField();
        jButtonSimpan = new javax.swing.JButton();
        jToggleButtonDelete = new javax.swing.JToggleButton();
        jToggleButtonBatal = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableLecturer = new javax.swing.JTable();
        jButtonPrev = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(656, 481));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Lecturer");

        jTextFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaActionPerformed(evt);
            }
        });

        jLabel5.setText("NIDN");

        jToggleButtonSearch.setText("Cari");
        jToggleButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSearchActionPerformed(evt);
            }
        });

        jButtonSimpan.setText("Simpan");
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });

        jToggleButtonDelete.setForeground(new java.awt.Color(255, 0, 51));
        jToggleButtonDelete.setText("Delete");
        jToggleButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonDeleteActionPerformed(evt);
            }
        });

        jToggleButtonBatal.setText("Batal");
        jToggleButtonBatal.setToolTipText("");
        jToggleButtonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonBatalActionPerformed(evt);
            }
        });

        jLabel7.setText("NAMA");

        jLabel8.setText("NIK");

        jLabel9.setText("EXPERTISE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jToggleButtonBatal)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButtonDelete)
                        .addGap(12, 12, 12)
                        .addComponent(jButtonSimpan))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCardID)
                            .addComponent(jTextFieldNama, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(jTextFieldNIDN))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldExpertise))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldExpertise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButtonSearch))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCardID)
                        .addComponent(jLabel8)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNIDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSimpan)
                            .addComponent(jToggleButtonDelete)
                            .addComponent(jToggleButtonBatal))
                        .addGap(26, 26, 26))))
        );

        jScrollPane4.setPreferredSize(new java.awt.Dimension(300, 80));

        jTableLecturer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableLecturer.setFillsViewportHeight(true);
        jTableLecturer.setShowGrid(false);
        jTableLecturer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLecturerMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableLecturer);

        jButtonPrev.setText("<<Prev");
        jButtonPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrevActionPerformed(evt);
            }
        });

        jButtonNext.setText("Next>>");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel6.setText("InputData");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonPrev)
                        .addGap(35, 35, 35)
                        .addComponent(jButtonNext)
                        .addGap(214, 214, 214))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(262, 262, 262)))
                        .addGap(17, 17, 17))))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNext)
                    .addComponent(jButtonPrev))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
       try {

            String name = jTextFieldNama.getText();
            String nidn = jTextFieldNIDN.getText();
            String cardID = jTextFieldCardID.getText();
            String expertise = jTextFieldExpertise.getText();

            if (name.isEmpty() || name.equals("Nama") || nidn.isEmpty() || nidn.equals("NIDN") || cardID.isEmpty() || cardID.equals("CardID") || expertise.isEmpty() || expertise.equals("Expertise")) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Data kolom dosen harus terisi",
                        "Peringatan",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            Lecturer lecturer = new Lecturer(cardID, name, nidn, expertise);

            int hasil = 0;
            String messageSucces = "";
            if(this.nidnLama.equals("")){
                hasil = controller.create(lecturer);
                messageSucces = "Data dosen berhasil disimpan!"; 
            }else{
                hasil = controller.update(lecturer, this.nidnLama);
                messageSucces = "Data dosen berhasil diperbarui!"; 
            }
               
            if (hasil == 1) {
              
                javax.swing.JOptionPane.showMessageDialog(this, messageSucces);

                loadLecturerData();
                clearForm();
            } 

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Terjadi kesalahan sistem: " + e.getMessage(),
                    "Error Fatal",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jButtonPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrevActionPerformed
        // TODO add your handling code here:
        if (listDosen == null || listDosen.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Belum ada data dosen pada tabel");
            return;
        }
        if (currentIndex > 0) {
            currentIndex--;
            tampilkanData(currentIndex);
            jTableLecturer.setRowSelectionInterval(currentIndex, currentIndex);
            jTableLecturer.changeSelection(currentIndex, 0, false, false);
            jTableLecturer.scrollRectToVisible(jTableLecturer.getCellRect(currentIndex, 0, true));

            jTableLecturer.requestFocusInWindow();
        }
    }//GEN-LAST:event_jButtonPrevActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        // TODO add your handling code here:
        if (listDosen == null || listDosen.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Belum ada data dosen pada tabel");
            return;
        }
        if (currentIndex < listDosen.size() - 1) {
            currentIndex++;
            tampilkanData(currentIndex);
            jTableLecturer.setRowSelectionInterval(currentIndex, currentIndex);
            jTableLecturer.scrollRectToVisible(jTableLecturer.getCellRect(currentIndex, 0, true));

        }
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jToggleButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonDeleteActionPerformed
        // TODO add your handling code here:

        if (this.selectedNIDN == null || this.selectedNIDN.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih data tabel dosen terlebih dahulu", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Apakah anda yakin untuk menghapus data dosen ini ? ",
                "Delete Confirmation",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try {
                controller.delete(selectedNIDN);
                javax.swing.JOptionPane.showMessageDialog(this, "Lecturer deleted successfully!");

                this.selectedNIDN = null;
                this.clearForm();
                loadLecturerData();

            } catch (Exception ex) {
                System.err.println("Error saat menghapus data dosen: " + ex.getMessage());
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Deleted unsuccessfully! Terjadi kesalahan pada sistem.",
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jToggleButtonDeleteActionPerformed

    private void jTableLecturerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLecturerMouseClicked
        // TODO add your handling code here:
       int selecttedRow = jTableLecturer.getSelectedRow();
        if (selecttedRow >= 0) {
            this.selectedNIDN = jTableLecturer.getValueAt(selecttedRow, 2).toString();
            
            jTextFieldNama.setText(jTableLecturer.getValueAt(selecttedRow, 0).toString());
            jTextFieldCardID.setText(jTableLecturer.getValueAt(selecttedRow, 1).toString());
            
            jTextFieldNIDN.setText(this.selectedNIDN); 
            jTextFieldNIDN.setEditable(false); 
           
            jTextFieldExpertise.setText(jTableLecturer.getValueAt(selecttedRow, 3).toString());
            
            this.nidnLama = jTableLecturer.getValueAt(selecttedRow, 2).toString();
        }
    }//GEN-LAST:event_jTableLecturerMouseClicked

    private void jToggleButtonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonBatalActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_jToggleButtonBatalActionPerformed

    private void jToggleButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSearchActionPerformed
        // TODO add your handling code here:
       String keyword = jTextFieldSearch.getText().trim();
        List<Lecturer> dataHasil;
        
      
        if (keyword.isEmpty()) {
            dataHasil = controller.getLecturer();
        } else {
            
            dataHasil = controller.searchLecturer(keyword);
        }


        refreshLecturerTable(dataHasil);


        if (dataHasil.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Data dosen tidak ditemukan!",
                    "Pencarian",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jToggleButtonSearchActionPerformed

    private void jTextFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LecturerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LecturerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LecturerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LecturerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {

                    new LecturerForm().setVisible(true);
                } catch (java.sql.SQLException ex) {

                    java.util.logging.Logger.getLogger(LecturerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrev;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTableLecturer;
    private javax.swing.JTextField jTextFieldCardID;
    private javax.swing.JTextField jTextFieldExpertise;
    private javax.swing.JTextField jTextFieldNIDN;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JToggleButton jToggleButtonBatal;
    private javax.swing.JToggleButton jToggleButtonDelete;
    private javax.swing.JToggleButton jToggleButtonSearch;
    // End of variables declaration//GEN-END:variables
}
